development:
  adapter: postgresql
  encoding: unicode
  database: cookbook_app_development
  pool: 5
  host: localhost
  username: dylanoshea
  password:

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: cookbook_app_test
#   pool: 5
#   username: cookbook_app
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: cookbook_app_production
#   pool: 5
#   username: cookbook_app
#   password:
